const uploadedResp = {
    "Data": [
        {
            "ActivityID": 407719,
            "ActivityTypeID": 204,
            "CaseID": 157951,
            "Comment": "Document name: PRASEETHA_K U_Resume_11-08-2023-12-09-13.pdf\r\nComment: ",
            "CreatedBy": 3564,
            "CreatedDate": "2023-11-07T11:41:21.4",
            "Subject": "New document has been uploaded",
            "LastModifiedDate": null,
            "LastModifiedBy": null,
            "Time": null,
            "CreatedByName": "A.S",
            "Colors": "#191970",
            "TypeInitials": "FU",
            "TypeName": "New File Uploaded",
            "TaskID": null,
            "TaskType": null,
            "Pin": false,
            "Popup": null
        },
        {
            "ActivityID": 298320,
            "ActivityTypeID": 6,
            "CaseID": 157951,
            "Comment": "A new payment plan was scheduled as follows: \r\n\r\nOct 15, 2019 $500.00\r\n",
            "CreatedBy": 1,
            "CreatedDate": "2019-10-14T15:58:29.39",
            "Subject": "Payment plan changed",
            "LastModifiedDate": null,
            "LastModifiedBy": null,
            "Time": null,
            "CreatedByName": "L.Support",
            "Colors": "#8b008b",
            "TypeInitials": "PA",
            "TypeName": "Payment",
            "TaskID": null,
            "TaskType": null,
            "Pin": false,
            "Popup": null
        },
        {
            "ActivityID": 298319,
            "ActivityTypeID": 6,
            "CaseID": 157951,
            "Comment": "Amount: 500.0000 \r\nPaid by: Cash \r\nPaid Date: 10/14/2019",
            "CreatedBy": 1,
            "CreatedDate": "2019-10-14T15:51:08.563",
            "Subject": "Payment deleted $500.00",
            "LastModifiedDate": null,
            "LastModifiedBy": null,
            "Time": null,
            "CreatedByName": "L.Support",
            "Colors": "#8b008b",
            "TypeInitials": "PA",
            "TypeName": "Payment",
            "TaskID": null,
            "TaskType": null,
            "Pin": false,
            "Popup": null
        },
        {
            "ActivityID": 298318,
            "ActivityTypeID": 6,
            "CaseID": 157951,
            "Comment": "Paid by: Cash \r\nAmount: $500.00 \r\nComment: Manual Cash Payment Was Successful.",
            "CreatedBy": 1,
            "CreatedDate": "2019-10-14T15:51:01.563",
            "Subject": "Payment made $500.00",
            "LastModifiedDate": null,
            "LastModifiedBy": null,
            "Time": null,
            "CreatedByName": "L.Support",
            "Colors": "#8b008b",
            "TypeInitials": "PA",
            "TypeName": "Payment",
            "TaskID": null,
            "TaskType": null,
            "Pin": false,
            "Popup": null
        },
        {
            "ActivityID": 298317,
            "ActivityTypeID": 6,
            "CaseID": 157951,
            "Comment": "Amount: 500.0000 \r\nPaid by: Cash \r\nPaid Date: 10/14/2019",
            "CreatedBy": 1,
            "CreatedDate": "2019-10-14T15:50:53.673",
            "Subject": "Payment deleted $500.00",
            "LastModifiedDate": null,
            "LastModifiedBy": null,
            "Time": null,
            "CreatedByName": "L.Support",
            "Colors": "#8b008b",
            "TypeInitials": "PA",
            "TypeName": "Payment",
            "TaskID": null,
            "TaskType": null,
            "Pin": false,
            "Popup": null
        },
        {
            "ActivityID": 298316,
            "ActivityTypeID": 6,
            "CaseID": 157951,
            "Comment": "Paid by: Cash \r\nAmount: $500.00 \r\nComment: Manual Cash Payment Was Successful.",
            "CreatedBy": 1,
            "CreatedDate": "2019-10-14T15:49:13.733",
            "Subject": "Payment made $500.00",
            "LastModifiedDate": null,
            "LastModifiedBy": null,
            "Time": null,
            "CreatedByName": "L.Support",
            "Colors": "#8b008b",
            "TypeInitials": "PA",
            "TypeName": "Payment",
            "TaskID": null,
            "TaskType": null,
            "Pin": false,
            "Popup": null
        },
        {
            "ActivityID": 298315,
            "ActivityTypeID": 6,
            "CaseID": 157951,
            "Comment": "Amount: 500.0000 \r\nPaid by: Cash \r\nPaid Date: 10/14/2019",
            "CreatedBy": 1,
            "CreatedDate": "2019-10-14T15:48:58.047",
            "Subject": "Payment deleted $500.00",
            "LastModifiedDate": null,
            "LastModifiedBy": null,
            "Time": null,
            "CreatedByName": "L.Support",
            "Colors": "#8b008b",
            "TypeInitials": "PA",
            "TypeName": "Payment",
            "TaskID": null,
            "TaskType": null,
            "Pin": false,
            "Popup": null
        },
        {
            "ActivityID": 298314,
            "ActivityTypeID": 6,
            "CaseID": 157951,
            "Comment": "Paid by: Cash \r\nAmount: $500.00 \r\nComment: Manual Cash Payment Was Successful.",
            "CreatedBy": 1,
            "CreatedDate": "2019-10-14T15:48:06.093",
            "Subject": "Payment made $500.00",
            "LastModifiedDate": null,
            "LastModifiedBy": null,
            "Time": null,
            "CreatedByName": "L.Support",
            "Colors": "#8b008b",
            "TypeInitials": "PA",
            "TypeName": "Payment",
            "TaskID": null,
            "TaskType": null,
            "Pin": false,
            "Popup": null
        },
        {
            "ActivityID": 298313,
            "ActivityTypeID": 6,
            "CaseID": 157951,
            "Comment": "Amount: 500.0000 \r\nPaid by: Cash \r\nPaid Date: 10/14/2019",
            "CreatedBy": 1,
            "CreatedDate": "2019-10-14T15:42:26.033",
            "Subject": "Payment deleted $500.00",
            "LastModifiedDate": null,
            "LastModifiedBy": null,
            "Time": null,
            "CreatedByName": "L.Support",
            "Colors": "#8b008b",
            "TypeInitials": "PA",
            "TypeName": "Payment",
            "TaskID": null,
            "TaskType": null,
            "Pin": false,
            "Popup": null
        },
        {
            "ActivityID": 298312,
            "ActivityTypeID": 6,
            "CaseID": 157951,
            "Comment": "Paid by: Cash \r\nAmount: $500.00 \r\nComment: Manual Cash Payment Was Successful.",
            "CreatedBy": 1,
            "CreatedDate": "2019-10-14T15:42:04.627",
            "Subject": "Payment made $500.00",
            "LastModifiedDate": null,
            "LastModifiedBy": null,
            "Time": null,
            "CreatedByName": "L.Support",
            "Colors": "#8b008b",
            "TypeInitials": "PA",
            "TypeName": "Payment",
            "TaskID": null,
            "TaskType": null,
            "Pin": false,
            "Popup": null
        },
        {
            "ActivityID": 298311,
            "ActivityTypeID": 6,
            "CaseID": 157951,
            "Comment": "Amount: 500.0000 \r\nPaid by: Cash \r\nPaid Date: 10/14/2019",
            "CreatedBy": 1,
            "CreatedDate": "2019-10-14T15:41:37.563",
            "Subject": "Payment deleted $500.00",
            "LastModifiedDate": null,
            "LastModifiedBy": null,
            "Time": null,
            "CreatedByName": "L.Support",
            "Colors": "#8b008b",
            "TypeInitials": "PA",
            "TypeName": "Payment",
            "TaskID": null,
            "TaskType": null,
            "Pin": false,
            "Popup": null
        },
        {
            "ActivityID": 298310,
            "ActivityTypeID": 6,
            "CaseID": 157951,
            "Comment": "Paid by: Cash \r\nAmount: $500.00 \r\nComment: Manual Cash Payment Was Successful.",
            "CreatedBy": 1,
            "CreatedDate": "2019-10-14T15:41:30.5",
            "Subject": "Payment made $500.00",
            "LastModifiedDate": null,
            "LastModifiedBy": null,
            "Time": null,
            "CreatedByName": "L.Support",
            "Colors": "#8b008b",
            "TypeInitials": "PA",
            "TypeName": "Payment",
            "TaskID": null,
            "TaskType": null,
            "Pin": false,
            "Popup": null
        },
        {
            "ActivityID": 298309,
            "ActivityTypeID": 6,
            "CaseID": 157951,
            "Comment": "Amount: 500.0000 \r\nPaid by: Cash \r\nPaid Date: 10/14/2019",
            "CreatedBy": 1,
            "CreatedDate": "2019-10-14T15:41:22.343",
            "Subject": "Payment deleted $500.00",
            "LastModifiedDate": null,
            "LastModifiedBy": null,
            "Time": null,
            "CreatedByName": "L.Support",
            "Colors": "#8b008b",
            "TypeInitials": "PA",
            "TypeName": "Payment",
            "TaskID": null,
            "TaskType": null,
            "Pin": false,
            "Popup": null
        },
        {
            "ActivityID": 298308,
            "ActivityTypeID": 6,
            "CaseID": 157951,
            "Comment": "Paid by: Cash \r\nAmount: $500.00 \r\nComment: Manual Cash Payment Was Successful.",
            "CreatedBy": 1,
            "CreatedDate": "2019-10-14T15:40:54.547",
            "Subject": "Payment made $500.00",
            "LastModifiedDate": null,
            "LastModifiedBy": null,
            "Time": null,
            "CreatedByName": "L.Support",
            "Colors": "#8b008b",
            "TypeInitials": "PA",
            "TypeName": "Payment",
            "TaskID": null,
            "TaskType": null,
            "Pin": false,
            "Popup": null
        },
        {
            "ActivityID": 298307,
            "ActivityTypeID": 6,
            "CaseID": 157951,
            "Comment": "Amount: 500.0000 \r\nPaid by: Cash \r\nPaid Date: 10/14/2019",
            "CreatedBy": 1,
            "CreatedDate": "2019-10-14T15:40:39.547",
            "Subject": "Payment deleted $500.00",
            "LastModifiedDate": null,
            "LastModifiedBy": null,
            "Time": null,
            "CreatedByName": "L.Support",
            "Colors": "#8b008b",
            "TypeInitials": "PA",
            "TypeName": "Payment",
            "TaskID": null,
            "TaskType": null,
            "Pin": false,
            "Popup": null
        },
        {
            "ActivityID": 298306,
            "ActivityTypeID": 6,
            "CaseID": 157951,
            "Comment": "Paid by: Cash \r\nAmount: $500.00 \r\nComment: Manual Cash Payment Was Successful.",
            "CreatedBy": 1,
            "CreatedDate": "2019-10-14T15:40:06.11",
            "Subject": "Payment made $500.00",
            "LastModifiedDate": null,
            "LastModifiedBy": null,
            "Time": null,
            "CreatedByName": "L.Support",
            "Colors": "#8b008b",
            "TypeInitials": "PA",
            "TypeName": "Payment",
            "TaskID": null,
            "TaskType": null,
            "Pin": false,
            "Popup": null
        },
        {
            "ActivityID": 298305,
            "ActivityTypeID": 6,
            "CaseID": 157951,
            "Comment": "Amount: 500.0000 \r\nPaid by: Cash \r\nPaid Date: 10/14/2019",
            "CreatedBy": 1,
            "CreatedDate": "2019-10-14T15:39:49.08",
            "Subject": "Payment deleted $500.00",
            "LastModifiedDate": null,
            "LastModifiedBy": null,
            "Time": null,
            "CreatedByName": "L.Support",
            "Colors": "#8b008b",
            "TypeInitials": "PA",
            "TypeName": "Payment",
            "TaskID": null,
            "TaskType": null,
            "Pin": false,
            "Popup": null
        },
        {
            "ActivityID": 298304,
            "ActivityTypeID": 6,
            "CaseID": 157951,
            "Comment": "Paid by: Cash \r\nAmount: $500.00 \r\nComment: Manual Cash Payment Was Successful.",
            "CreatedBy": 1,
            "CreatedDate": "2019-10-14T15:39:28.563",
            "Subject": "Payment made $500.00",
            "LastModifiedDate": null,
            "LastModifiedBy": null,
            "Time": null,
            "CreatedByName": "L.Support",
            "Colors": "#8b008b",
            "TypeInitials": "PA",
            "TypeName": "Payment",
            "TaskID": null,
            "TaskType": null,
            "Pin": false,
            "Popup": null
        },
        {
            "ActivityID": 298303,
            "ActivityTypeID": 6,
            "CaseID": 157951,
            "Comment": "Amount: 500.0000 \r\nPaid by: Cash \r\nPaid Date: 10/14/2019",
            "CreatedBy": 1,
            "CreatedDate": "2019-10-14T15:39:02.953",
            "Subject": "Payment deleted $500.00",
            "LastModifiedDate": null,
            "LastModifiedBy": null,
            "Time": null,
            "CreatedByName": "L.Support",
            "Colors": "#8b008b",
            "TypeInitials": "PA",
            "TypeName": "Payment",
            "TaskID": null,
            "TaskType": null,
            "Pin": false,
            "Popup": null
        },
        {
            "ActivityID": 298302,
            "ActivityTypeID": 6,
            "CaseID": 157951,
            "Comment": "Paid by: Cash \r\nAmount: $500.00 \r\nComment: Manual Cash Payment Was Successful.",
            "CreatedBy": 1,
            "CreatedDate": "2019-10-14T15:37:51.437",
            "Subject": "Payment made $500.00",
            "LastModifiedDate": null,
            "LastModifiedBy": null,
            "Time": null,
            "CreatedByName": "L.Support",
            "Colors": "#8b008b",
            "TypeInitials": "PA",
            "TypeName": "Payment",
            "TaskID": null,
            "TaskType": null,
            "Pin": false,
            "Popup": null
        },
        {
            "ActivityID": 298301,
            "ActivityTypeID": 2,
            "CaseID": 157951,
            "Comment": "",
            "CreatedBy": 1,
            "CreatedDate": "2019-10-14T15:35:02.78",
            "Subject": "Status changed from \"[Pending Approval]-Pending Approval\"  to  \"[Active Case]-te\"",
            "LastModifiedDate": "2019-10-14T15:35:02.78",
            "LastModifiedBy": 1,
            "Time": null,
            "CreatedByName": "L.Support",
            "Colors": "#008b8b",
            "TypeInitials": "GN",
            "TypeName": "General",
            "TaskID": null,
            "TaskType": null,
            "Pin": false,
            "Popup": null
        },
        {
            "ActivityID": 298300,
            "ActivityTypeID": 3,
            "CaseID": 157951,
            "Comment": "Client Portal Invitation Sent",
            "CreatedBy": 1,
            "CreatedDate": "2019-10-14T15:35:02.703",
            "Subject": "Client Portal Invitation Sent",
            "LastModifiedDate": "2019-10-14T15:35:02.703",
            "LastModifiedBy": 1,
            "Time": null,
            "CreatedByName": "L.Support",
            "Colors": "#191970",
            "TypeInitials": "DO",
            "TypeName": "Document sent",
            "TaskID": null,
            "TaskType": null,
            "Pin": false,
            "Popup": null
        },
        {
            "ActivityID": 298299,
            "ActivityTypeID": 2,
            "CaseID": 157951,
            "Comment": "<b>Services contracted for:</b><br/>Service (1): <b>n/a</b> <br/>Service (2): <b>Tax Return Prep.</b> <br/>Service (3): <b>irs</b> <br/>Other: <b>CNC if not PPIA/SIA program</b><br/><br/><b>Assignments:</b><br/>Set. Officer: <b>--Unassigned--</b><br/>Case Worker: <b></b><br/>Case Manager: <b></b><br/>CPA/Attorney/EA: <b></b>",
            "CreatedBy": 1,
            "CreatedDate": "2019-10-14T15:35:01.187",
            "Subject": "Approved - Converted to client",
            "LastModifiedDate": "2019-10-14T15:35:01.187",
            "LastModifiedBy": 1,
            "Time": null,
            "CreatedByName": "L.Support",
            "Colors": "#008b8b",
            "TypeInitials": "GN",
            "TypeName": "General",
            "TaskID": null,
            "TaskType": null,
            "Pin": false,
            "Popup": null
        },
        {
            "ActivityID": 298298,
            "ActivityTypeID": 2,
            "CaseID": 157951,
            "Comment": "",
            "CreatedBy": 1,
            "CreatedDate": "2019-10-14T15:34:50.33",
            "Subject": "Status changed from \"[New Lead(Opened)]-Pending: Docs: Substantiation\"  to  \"[Pending Approval]-Pending Approval\"",
            "LastModifiedDate": "2019-10-14T15:34:50.33",
            "LastModifiedBy": 1,
            "Time": null,
            "CreatedByName": "L.Support",
            "Colors": "#008b8b",
            "TypeInitials": "GN",
            "TypeName": "General",
            "TaskID": null,
            "TaskType": null,
            "Pin": false,
            "Popup": null
        },
        {
            "ActivityID": 298297,
            "ActivityTypeID": 2,
            "CaseID": 157951,
            "Comment": "<b>Services contracted for:</b><br/>Service (1): <b>n/a</b> <br/>Service (2): <b>Tax Return Prep.</b> <br/>Service (3): <b>irs</b> <br/>Other: <b>CNC if not PPIA/SIA program</b><br/><br/><b>Assignments:</b><br/>Set. Officer: <b>--Unassigned--</b><br/>Case Worker: <b></b><br/>Case Manager: <b></b><br/>CPA/Attorney/EA: <b></b>",
            "CreatedBy": 1,
            "CreatedDate": "2019-10-14T15:34:49.157",
            "Subject": "Submitted for approval",
            "LastModifiedDate": "2019-10-14T15:34:49.157",
            "LastModifiedBy": 1,
            "Time": null,
            "CreatedByName": "L.Support",
            "Colors": "#008b8b",
            "TypeInitials": "GN",
            "TypeName": "General",
            "TaskID": null,
            "TaskType": null,
            "Pin": false,
            "Popup": null
        },
        {
            "ActivityID": 298296,
            "ActivityTypeID": 6,
            "CaseID": 157951,
            "Comment": "A new payment plan was scheduled as follows: \r\n\r\nOct 14, 2019 $500.00\r\nNov 14, 2019 $500.00\r\n",
            "CreatedBy": 1,
            "CreatedDate": "2019-10-14T15:34:23.173",
            "Subject": "Payment plan changed",
            "LastModifiedDate": null,
            "LastModifiedBy": null,
            "Time": null,
            "CreatedByName": "L.Support",
            "Colors": "#8b008b",
            "TypeInitials": "PA",
            "TypeName": "Payment",
            "TaskID": null,
            "TaskType": null,
            "Pin": false,
            "Popup": null
        },
        {
            "ActivityID": 298295,
            "ActivityTypeID": 6,
            "CaseID": 157951,
            "Comment": "A new payment plan was scheduled as follows: \r\n\r\nJun 19, 2019 $200.00\r\nOct 14, 2019 $266.67\r\nNov 14, 2019 $266.67\r\nDec 14, 2019 $266.66\r\n",
            "CreatedBy": 1,
            "CreatedDate": "2019-10-14T15:33:03.61",
            "Subject": "Payment plan changed",
            "LastModifiedDate": null,
            "LastModifiedBy": null,
            "Time": null,
            "CreatedByName": "L.Support",
            "Colors": "#8b008b",
            "TypeInitials": "PA",
            "TypeName": "Payment",
            "TaskID": null,
            "TaskType": null,
            "Pin": false,
            "Popup": null
        },
        {
            "ActivityID": 298294,
            "ActivityTypeID": 6,
            "CaseID": 157951,
            "Comment": "Invoice type: Consolidation \r\nQuantity: 1 \r\nUnit Price: 1000 \r\nTotal: $1,000.00 \r\nDescription:  ",
            "CreatedBy": 1,
            "CreatedDate": "2019-10-14T15:31:46.267",
            "Subject": "New invoice item added",
            "LastModifiedDate": null,
            "LastModifiedBy": null,
            "Time": null,
            "CreatedByName": "L.Support",
            "Colors": "#8b008b",
            "TypeInitials": "PA",
            "TypeName": "Payment",
            "TaskID": null,
            "TaskType": null,
            "Pin": false,
            "Popup": null
        }
    ],
    "Total": 28,
    "TotalSum": 0.0,
    "EnableCustomActivityColor": false
}
export default uploadedResp;