const TaskResp =
{
    "Data": [
        {
            "ModifiedBy": 3564,
            "AssignedToMeCount": 1,
            "TaskCategory": null,
            "GroupName": null,
            "CategoryName": null,
            "TaskID": 13631,
            "FolderID": 25,
            "TaskType": "Task",
            "TaskTypeID": 1,
            "CaseName": "157951 - john smith",
            "CaseID": 157951,
            "StatusID": 0,
            "Subject": "test",
            "AssignedTo": "<span style=\"font-weight:bold;font-size:10pt\">Me</span>",
            "AssignedToMe": true,
            "CreatedBy": "Athira S",
            "CreatedByID": 3564,
            "DueDate": "2023-11-26T00:00:00",
            "EndDate": null,
            "ModifiedDate": "2023-11-21T09:46:38.907",
            "ReminderDate": "2023-11-24T07:30:00",
            "PriorityID": 0,
            "DueDateDescription": "4 - This Week",
            "AllDayEvent": false,
            "CTECID": null,
            "CasemanagerID": null,
            "CaseworkerID": null,
            "SetOfficerID": 0,
            "AttorneyID": null,
            "TaxpreparerID": null,
            "TeamID": 0,
            "Team": "Main Office",
            "TaskCategoryID": null,
            "CaseStatus": "[Active Case] - Appeal1",
            "CaseStatusID": 15,
            "CompletedDateDescription": "Not Completed",
            "CompletedBy": "",
            "SettlementOfficer": null,
            "Attorney": null,
            "CaseManager": null,
            "TaxPreparer": null,
            "CaseWorker": null
        },
        {
            "ModifiedBy": 3564,
            "AssignedToMeCount": 1,
            "TaskCategory": null,
            "GroupName": null,
            "CategoryName": null,
            "TaskID": 13633,
            "FolderID": 25,
            "TaskType": "Event",
            "TaskTypeID": 2,
            "CaseName": "157951 - john smith",
            "CaseID": 157951,
            "StatusID": 0,
            "Subject": "test event",
            "AssignedTo": "<span style=\"font-weight:bold;font-size:10pt\">Me</span>",
            "AssignedToMe": true,
            "CreatedBy": "Athira S",
            "CreatedByID": 3564,
            "DueDate": "2023-11-29T07:30:00",
            "EndDate": "2023-12-05T08:30:00",
            "ModifiedDate": "2023-11-21T10:40:21.613",
            "ReminderDate": "2023-11-29T07:00:00",
            "PriorityID": 0,
            "DueDateDescription": "5 - Next Week",
            "AllDayEvent": false,
            "CTECID": null,
            "CasemanagerID": null,
            "CaseworkerID": null,
            "SetOfficerID": 0,
            "AttorneyID": null,
            "TaxpreparerID": null,
            "TeamID": 0,
            "Team": "Main Office",
            "TaskCategoryID": null,
            "CaseStatus": "[Active Case] - Appeal1",
            "CaseStatusID": 15,
            "CompletedDateDescription": "Not Completed",
            "CompletedBy": "",
            "SettlementOfficer": null,
            "Attorney": null,
            "CaseManager": null,
            "TaxPreparer": null,
            "CaseWorker": null
        },
        {
            "ModifiedBy": 3564,
            "AssignedToMeCount": 1,
            "TaskCategory": null,
            "GroupName": null,
            "CategoryName": null,
            "TaskID": 13632,
            "FolderID": 25,
            "TaskType": "Task",
            "TaskTypeID": 1,
            "CaseName": "157951 - john smith",
            "CaseID": 157951,
            "StatusID": 0,
            "Subject": "test 2",
            "AssignedTo": "<span style=\"font-weight:bold;font-size:10pt\">Me</span>",
            "AssignedToMe": true,
            "CreatedBy": "Athira S",
            "CreatedByID": 3564,
            "DueDate": "2023-11-30T00:00:00",
            "EndDate": null,
            "ModifiedDate": "2023-11-21T09:47:33.33",
            "ReminderDate": "2023-11-26T07:30:00",
            "PriorityID": 0,
            "DueDateDescription": "5 - Next Week",
            "AllDayEvent": false,
            "CTECID": null,
            "CasemanagerID": null,
            "CaseworkerID": null,
            "SetOfficerID": 0,
            "AttorneyID": null,
            "TaxpreparerID": null,
            "TeamID": 0,
            "Team": "Main Office",
            "TaskCategoryID": null,
            "CaseStatus": "[Active Case] - Appeal1",
            "CaseStatusID": 15,
            "CompletedDateDescription": "Not Completed",
            "CompletedBy": "",
            "SettlementOfficer": null,
            "Attorney": null,
            "CaseManager": null,
            "TaxPreparer": null,
            "CaseWorker": null
        }
    ],
    "Total": 0,
    "TotalSum": 0.0,
    "EnableCustomActivityColor": false
}


    export default TaskResp;