const response ={
    "Error": false,
    "Result": [
        {
            "EventId": 0,
            "CaseId": null,
            "CaseLinkName": null,
            "CalendarId": 1,
            "Title": "Regular Updates",
            "StartDate": "2023-09-03T22:30:00-05:00",
            "EndDate": "2023-09-03T23:00:00-05:00",
            "IsAllDay": false,
            "Reminder": "",
            "Notes": "Google Event ",
            "CaseName": null,
            "ScheduledEventId": "event",
            "Color": null,
            "UserID": null
        },
        {
            "EventId": 0,
            "CaseId": null,
            "CaseLinkName": null,
            "CalendarId": 1,
            "Title": "Regular Updates",
            "StartDate": "2023-09-04T22:30:00-05:00",
            "EndDate": "2023-09-04T23:00:00-05:00",
            "IsAllDay": false,
            "Reminder": "",
            "Notes": "Google Event ",
            "CaseName": null,
            "ScheduledEventId": "event",
            "Color": null,
            "UserID": null
        },
        {
            "EventId": 0,
            "CaseId": null,
            "CaseLinkName": null,
            "CalendarId": 1,
            "Title": "Regular Updates",
            "StartDate": "2023-09-07T22:30:00-05:00",
            "EndDate": "2023-09-07T23:00:00-05:00",
            "IsAllDay": false,
            "Reminder": "",
            "Notes": "Google Event ",
            "CaseName": null,
            "ScheduledEventId": "event",
            "Color": null,
            "UserID": null
        },
        {
            "EventId": 0,
            "CaseId": null,
            "CaseLinkName": null,
            "CalendarId": 1,
            "Title": "Regular Updates",
            "StartDate": "2023-09-17T22:30:00-05:00",
            "EndDate": "2023-09-17T23:00:00-05:00",
            "IsAllDay": false,
            "Reminder": "",
            "Notes": "Google Event ",
            "CaseName": null,
            "ScheduledEventId": "event",
            "Color": null,
            "UserID": null
        },
        {
            "EventId": 0,
            "CaseId": null,
            "CaseLinkName": null,
            "CalendarId": 1,
            "Title": "Regular Updates",
            "StartDate": "2023-09-21T22:30:00-05:00",
            "EndDate": "2023-09-21T23:00:00-05:00",
            "IsAllDay": false,
            "Reminder": "",
            "Notes": "Google Event ",
            "CaseName": null,
            "ScheduledEventId": "event",
            "Color": null,
            "UserID": null
        },
        {
            "EventId": 0,
            "CaseId": null,
            "CaseLinkName": null,
            "CalendarId": 1,
            "Title": "Regular Updates",
            "StartDate": "2023-09-24T22:30:00-05:00",
            "EndDate": "2023-09-24T23:00:00-05:00",
            "IsAllDay": false,
            "Reminder": "",
            "Notes": "Google Event ",
            "CaseName": null,
            "ScheduledEventId": "event",
            "Color": null,
            "UserID": null
        },
        {
            "EventId": 0,
            "CaseId": null,
            "CaseLinkName": null,
            "CalendarId": 1,
            "Title": "Regular Updates",
            "StartDate": "2023-09-25T22:30:00-05:00",
            "EndDate": "2023-09-25T23:00:00-05:00",
            "IsAllDay": false,
            "Reminder": "",
            "Notes": "Google Event ",
            "CaseName": null,
            "ScheduledEventId": "event",
            "Color": null,
            "UserID": null
        },
        {
            "EventId": 0,
            "CaseId": null,
            "CaseLinkName": null,
            "CalendarId": 1,
            "Title": "Regular Updates",
            "StartDate": "2023-09-26T22:30:00-05:00",
            "EndDate": "2023-09-26T23:00:00-05:00",
            "IsAllDay": false,
            "Reminder": "",
            "Notes": "Google Event ",
            "CaseName": null,
            "ScheduledEventId": "event",
            "Color": null,
            "UserID": null
        },
        {
            "EventId": 0,
            "CaseId": null,
            "CaseLinkName": null,
            "CalendarId": 1,
            "Title": "Regular Updates",
            "StartDate": "2023-09-27T22:30:00-05:00",
            "EndDate": "2023-09-27T23:00:00-05:00",
            "IsAllDay": false,
            "Reminder": "",
            "Notes": "Google Event ",
            "CaseName": null,
            "ScheduledEventId": "event",
            "Color": null,
            "UserID": null
        },
        {
            "EventId": 0,
            "CaseId": null,
            "CaseLinkName": null,
            "CalendarId": 1,
            "Title": "Regular Updates",
            "StartDate": "2023-09-28T22:30:00-05:00",
            "EndDate": "2023-09-28T23:00:00-05:00",
            "IsAllDay": false,
            "Reminder": "",
            "Notes": "Google Event ",
            "CaseName": null,
            "ScheduledEventId": "event",
            "Color": null,
            "UserID": null
        },
        {
            "EventId": 0,
            "CaseId": null,
            "CaseLinkName": null,
            "CalendarId": 1,
            "Title": "Team meeting",
            "StartDate": "2023-09-01T00:15:00-05:00",
            "EndDate": "2023-09-01T07:30:00-05:00",
            "IsAllDay": false,
            "Reminder": "",
            "Notes": "Google Event ",
            "CaseName": null,
            "ScheduledEventId": "event",
            "Color": null,
            "UserID": null
        },
        {
            "EventId": 0,
            "CaseId": null,
            "CaseLinkName": null,
            "CalendarId": 1,
            "Title": "Team meeting",
            "StartDate": "2023-09-04T00:15:00-05:00",
            "EndDate": "2023-09-04T07:30:00-05:00",
            "IsAllDay": false,
            "Reminder": "",
            "Notes": "Google Event ",
            "CaseName": null,
            "ScheduledEventId": "event",
            "Color": null,
            "UserID": null
        },
        {
            "EventId": 0,
            "CaseId": null,
            "CaseLinkName": null,
            "CalendarId": 1,
            "Title": "Team meeting",
            "StartDate": "2023-09-05T00:15:00-05:00",
            "EndDate": "2023-09-05T07:30:00-05:00",
            "IsAllDay": false,
            "Reminder": "",
            "Notes": "Google Event ",
            "CaseName": null,
            "ScheduledEventId": "event",
            "Color": null,
            "UserID": null
        },
        {
            "EventId": 0,
            "CaseId": null,
            "CaseLinkName": null,
            "CalendarId": 1,
            "Title": "Team meeting",
            "StartDate": "2023-09-06T00:15:00-05:00",
            "EndDate": "2023-09-06T07:30:00-05:00",
            "IsAllDay": false,
            "Reminder": "",
            "Notes": "Google Event ",
            "CaseName": null,
            "ScheduledEventId": "event",
            "Color": null,
            "UserID": null
        },
        {
            "EventId": 0,
            "CaseId": null,
            "CaseLinkName": null,
            "CalendarId": 1,
            "Title": "Team meeting",
            "StartDate": "2023-09-07T00:15:00-05:00",
            "EndDate": "2023-09-07T07:30:00-05:00",
            "IsAllDay": false,
            "Reminder": "",
            "Notes": "Google Event ",
            "CaseName": null,
            "ScheduledEventId": "event",
            "Color": null,
            "UserID": null
        }
    ],
    "ErrorMessage": ""
}
export default response;